export default {
    UPDATE_QUOTE_DETAIL: 'UPDATE_QUOTE_DETAIL',
    UPDATE_QUOTE_HISTORY: 'UPDATE_QUOTE_HISTORY',
    UPDATE_QUOTE_RECENT_HISTORY: 'UPDATE_QUOTE_RECENT_HISTORY',
    UPDATE_FUND_BLACKROCK_TODAY_NAV: 'UPDATE_FUND_BLACKROCK_TODAY_NAV',
    UPDATE_FUND_CIFM_TODAY_NAV: 'UPDATE_FUND_CIFM_TODAY_NAV',
    FETCH_POTENTIAL_QUOTES: 'FETCH_POTENTIAL_QUOTES',
    SYNC_WP_NEWS: 'SYNC_WP_NEWS',
    CLICK_WP_NEWS: 'CLICK_WP_NEWS',
};